name: signature_pad
author: John Ryan <john.p.ryan4@gmail.com>
description: A flutter and HTML 5 canvas signature library
version: 2.0.0+1
homepage: https://github.com/johnpryan/signature-pad-dart
dependencies:
  stream_transform: ^0.0.9
dev_dependencies:
  browser: ^0.10.0
  build_runner: any
  build_web_compilers: any
environment:
  sdk: '>=1.23.0 <2.0.0'
