name: signature_pad
author: John Ryan <john.p.ryan4@gmail.com>
description: An HTML 5 canvas signature library
version: 1.0.1
homepage: https://github.com/johnpryan/signature-pad-dart
dependencies:
  rate_limit: ^0.1.0
dev_dependencies:
  browser: ^0.10.0
environment:
  sdk: ">=1.22.0"
